version: "3.9"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: psqladmin
      POSTGRES_PASSWORD: psqlpassword
      POSTGRES_DB: psqlstorage
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15433:80"
    depends_on:
      - database
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/